create table simulation_integration.missile_integration
(
    sortie_number                  varchar(50)  not null comment '架次号',
    event_ts                       timestamp(3) not null comment '事件时间戳',
    aircraft_id                    varchar(50)  null comment '飞机ID',
    message_time                   time(3)      null comment '消息时间',
    satellite_guidance_time        time(3)      null comment '卫导时间',
    local_time                     time(3)      null comment '本地时间',
    message_sequence_number        bigint       null comment '消息序列号',
    weapon_id                      varchar(50)  null comment '武器ID',
    weapon_type                    varchar(50)  null comment '武器类型',
    target_id                      varchar(50)  null comment '目标ID',
    pylon_id                       varchar(50)  null comment '挂架ID',
    longitude                      varchar(50)  null comment '经度',
    latitude                       varchar(50)  null comment '纬度',
    altitude                       varchar(50)  null comment '高度',
    heading                        varchar(50)  null comment '航向',
    pitch                          varchar(50)  null comment '俯仰',
    roll                           varchar(50)  null comment '横滚',
    missile_speed                  varchar(50)  null comment '弹速度',
    aircraft_ground_speed          varchar(50)  null comment '载机地速',
    north_speed                    varchar(50)  null comment '北速',
    sky_speed                      varchar(50)  null comment '天速',
    east_speed                     varchar(50)  null comment '东速',
    north_wind_speed               varchar(50)  null comment '北向风速',
    vertical_wind_speed            varchar(50)  null comment '天向风速',
    east_wind_speed                varchar(50)  null comment '东向风速',
    aircraft_north_speed           varchar(50)  null comment '载机北速',
    aircraft_vertical_speed        varchar(50)  null comment '载机天速',
    aircraft_east_speed            varchar(50)  null comment '载机东速',
    missile_target_distance        varchar(50)  null comment '弹目距离',
    target_distance                varchar(50)  null comment '目标距离',
    target_longitude               varchar(50)  null comment '目标经度',
    target_latitude                varchar(50)  null comment '目标纬度',
    target_altitude                varchar(50)  null comment '目标高度',
    target_elevation_angle         varchar(50)  null comment '目标俯仰角',
    target_azimuth_angle           varchar(50)  null comment '目标方位角',
    target_tspi_status             varchar(50)  null comment '目标TSPI状态',
    target_real_or_virtual         varchar(50)  null comment '目标实虚属性',
    target_coordinate_validity     varchar(50)  null comment '目标经纬高有效标识',
    intercepted_weapon_id          varchar(50)  null comment '被拦截武器ID',
    seeker_azimuth                 varchar(50)  null comment '导引头视线方位角',
    seeker_elevation               varchar(50)  null comment '导引头视线俯仰角',
    seeker_id                      varchar(50)  null comment '导引头号',
    seeker_head_number             varchar(50)  null comment '导引头号',
    seeker_azimuth_center          varchar(50)  null comment '导引头方位中心',
    seeker_pitch_center            varchar(50)  null comment '导引头俯仰中心',
    interception_status            varchar(50)  null comment '截获状态',
    interception_flag              varchar(50)  null comment '截获标志',
    non_interception_reason        varchar(50)  null comment '未截获原因',
    hit_result                     varchar(50)  null comment '命中结果',
    miss_reason                    varchar(50)  null comment '未命中原因',
    miss_distance                  varchar(50)  null comment '脱靶量',
    matching_failure_reason        varchar(50)  null comment '匹配失败原因',
    termination_flag               varchar(50)  null comment '终止标志',
    distance_interception_flag     varchar(50)  null comment '距离截获标志',
    speed_interception_flag        varchar(50)  null comment '速度截获标志',
    angle_interception_flag        varchar(50)  null comment '角度截获标志',
    command_machine_status         varchar(50)  null comment '指令机状态',
    ground_angle_satisfaction_flag varchar(50)  null comment '擦地角满足标志',
    zero_crossing_flag             varchar(50)  null comment '过零标志',
    aircraft_angle_of_attack       varchar(50)  null comment '载机攻角',
    impact_angle_validity          varchar(50)  null comment '落角有效性',
    entry_angle                    varchar(50)  null comment '进入角',
    impact_angle                   varchar(50)  null comment '落角',
    direction_validity             varchar(50)  null comment '方向有效性',
    missile_attack_mode            varchar(50)  null comment '导弹攻击模式',
    trajectory_type                varchar(50)  null comment '弹道类型',
    jamming_effective              varchar(50)  null comment '干扰是否有效',
    jamming                        varchar(50)  null comment '干扰',
    afterburner                    varchar(50)  null comment '加力',
    head_on                        varchar(50)  null comment '迎头',
    intercepting_member_id         varchar(50)  null comment '截获成员ID',
    intercepting_equipment_id      varchar(50)  null comment '截获装备ID',
    intercepting_equipment_type    varchar(50)  null comment '截获装备类型',
    launcher_id                    varchar(50)  null comment '发射方ID',
    ground_defense_equipment_type  varchar(50)  null comment '地导装备类型',
    ground_defense_equipment_id    varchar(50)  null comment '地导装备ID',
    source_table                   varchar(50)  null comment '数据来源表',
    primary key (sortie_number, event_ts)
)
    comment '导弹数据整合表' partition by key (`sortie_number`) partitions 8;

